Use f-strings on constants for better readability
rany2/edge-tts pull request #260
Opened 2024-10-02 19:07 UTC by blaisewf

It's not a very significant change, but I think it makes it easier to read/modify the url more easily

2024-10-02 19:49 UTC, andresayac approved these changes

2024-10-07 08:52 UTC, alxpez approved these changes

2024-10-07 09:26 UTC, rany2 commented
Please fix CI by create a base URL constant and using that for both voice list and websocket URL. This way you won't hit the maximum characters/line limit.

2024-10-07 20:05 UTC, rany2 requested changes
Required because WSS uses the wss:// scheme instead.

2024-10-07 20:05 UTC, rany2 commented on src/edge_tts/constants.py
> +BASE_URL = "https://speech.platform.bing.com/consumer/speech/synthesize"
```suggestion
BASE_URL = "speech.platform.bing.com/consumer/speech/synthesize"
```

2024-10-07 20:05 UTC, rany2 commented on src/edge_tts/constants.py
> +VOICE_LIST = f"{BASE_URL}/readaloud/voices/list?trustedclienttoken={TRUSTED_CLIENT_TOKEN}"
```suggestion
VOICE_LIST = f"https://{BASE_URL}/readaloud/voices/list?trustedclienttoken={TRUSTED_CLIENT_TOKEN}"
```

2024-10-09 08:18 UTC, rany2 approved these changes

2024-10-09 08:19 UTC, merged

2024-10-09 08:19 UTC, rany2 commented
Thanks!